import os
import lib.core.file_manipulation as file_manip
import tkinter as tk

NEW_PROJECT_DEFAULT_FOLDER = file_manip.PATH_HOME
DOCUMENTS_FOLDER = file_manip.PATH_DOCUMENTS
PROJECT_FOLDER = os.path.normpath(os.path.realpath(__file__) + '/../../../')

INT_SCREEN_WIDTH = tk.Tk().winfo_screenwidth()  # get the screen width
INT_SCREEN_HEIGHT = tk.Tk().winfo_screenheight()  # get the screen height
INT_WIN_WIDTH = 1024  # this variable is only for the if __name__ == "__main__"
INT_WIN_HEIGHT = 512  # this variable is only for the if __name__ == "__main__"

INT_MAX_STRETCH = 100000  # Spacer Max Stretch
INT_BUTTON_MIN_WIDTH = 50  # Minimum Button Width
INT_BUTTON_MIN_HEIGHT = 50  # Minimum Button Width
INT_ADD_REMOVE_BUTTON_SIZE = 48

ICON_ADD = PROJECT_FOLDER + "/icon/add_cross_128x128.png"
ICON_REMOVE = PROJECT_FOLDER + "/icon/remove_line_128x128.png"
ICON_ADD_FILLED = PROJECT_FOLDER + "/icon/add_cross_128x128_filled.png"
ICON_REMOVE_FILLED = PROJECT_FOLDER + "/icon/remove_line_128x128_filled.png"

# --- PLOT INFO --- #
PLOT_FONTSIZE_TITLE = 25
PLOT_FONTSIZE_TICKS = 20
PLOT_FONTSIZE_LABEL = 22.5
PLOT_FONTSIZE_LEGEND = 18
PLOT_SIZE_WIDTH = 12.40
PLOT_SIZE_HEIGHT = 12.40
PLOT_SIZE_DPI = 100

TRAIN_TEST_SEPARATOR = 'Train/Test Split'
REAL_STYLE = ['bs-']
PRED_STYLE = ['go-']

# --- MACHINE LEARNING FLAGS --- #
MLF_TEST_PERCENTAGE_MIN = 0.00
MLF_TEST_PERCENTAGE_MAX = 0.75
MLF_TEST_STEP_WIDGET = 0.05

MLF_HOLDOUT_PERCENTAGE_MIN = 0.00
MLF_HOLDOUT_PERCENTAGE_MAX = 0.75
MLF_HOLDOUT_STEP_WIDGET = 0.05

MLPF_METHOD_SEQUENTIAL = 'Sequential'
MLPF_METHOD_AVERAGE = 'Average'
MLPF_METHOD_SEQUENTIAL_AVERAGE = 'Sequential Average'

MLPF_METHOD_LIST = [MLPF_METHOD_SEQUENTIAL,
                    MLPF_METHOD_AVERAGE,
                    MLPF_METHOD_SEQUENTIAL_AVERAGE]

MLPF_MULTIFILE_TRAINING_PROCESSING_LINEAR = 'Linear Training-Testing'
MLPF_MULTIFILE_TRAINING_PROCESSING_PARALLEL = 'Parallel Training-Testing'

MLPF_MULTIFILE_TRAINING_PROCESSING_LIST = [MLPF_MULTIFILE_TRAINING_PROCESSING_LINEAR,
                                           MLPF_MULTIFILE_TRAINING_PROCESSING_PARALLEL]

MLPF_PERCENTAGE_DISTRIBUTION_RANDOM_FROM_START = 'Randomized Start'
MLPF_PERCENTAGE_DISTRIBUTION_RANDOM_FROM_MIDDLE = 'Randomized Middle'
MLPF_PERCENTAGE_DISTRIBUTION_RANDOM_FROM_END = 'Randomized End'
MLPF_PERCENTAGE_DISTRIBUTION_FROM_START = 'Dataset\'s Start'
MLPF_PERCENTAGE_DISTRIBUTION_FROM_MIDDLE = 'Dataset\'s Middle'
MLPF_PERCENTAGE_DISTRIBUTION_FROM_END = 'Dataset\'s End'

MLPF_PERCENTAGE_DISTRIBUTION_LIST = [MLPF_PERCENTAGE_DISTRIBUTION_FROM_START,
                                     MLPF_PERCENTAGE_DISTRIBUTION_FROM_MIDDLE,
                                     MLPF_PERCENTAGE_DISTRIBUTION_FROM_END,
                                     MLPF_PERCENTAGE_DISTRIBUTION_RANDOM_FROM_START,
                                     MLPF_PERCENTAGE_DISTRIBUTION_RANDOM_FROM_MIDDLE,
                                     MLPF_PERCENTAGE_DISTRIBUTION_RANDOM_FROM_END]

MLF_DEFAULT_EXPERIMENT_VALUE = 1
MLF_DEFAULT_TEST_PERCENTAGE = 0.25
MLF_DEFAULT_HOLDOUT_PERCENTAGE = 0.25
MLF_DEFAULT_EXPORT_FOLDER_PATH = DOCUMENTS_FOLDER + '/CrabsMLearning'
MLF_DEFAULT_METHOD = MLPF_METHOD_SEQUENTIAL
MLF_DEFAULT_METHOD_INDEX = 1
MLF_DEFAULT_MULTIFILE_TRAINING_PROCESSING = MLPF_MULTIFILE_TRAINING_PROCESSING_LINEAR
MLF_DEFAULT_TEST_PERCENTAGE_DISTRIBUTION = MLPF_PERCENTAGE_DISTRIBUTION_FROM_END
MLF_DEFAULT_HOLDOUT_PERCENTAGE_DISTRIBUTION = MLPF_PERCENTAGE_DISTRIBUTION_RANDOM_FROM_START
